### ISSUE TITLE
Prometheus configuration

### ISSUE THREAD

**Issue by seungjinyu** [Clymene-project/Clymene#42]
Hello I`m a DevOps engineer who got interested in Clymene 

I have read the blog post and came to this Github to use Clymene how it works on the k8s cluster 

But it seems like I have misconfigured the app but could not find the solution.

So the issue is that when I configure the prometheus remote url the agent saids that the option does not exist.

Were there any updates? 

below is my deployments.yaml file 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clymene-agent
  namespace: clymene
  labels:
    app: clymene-agent
spec:
  selector:
    matchLabels:
      app: clymene-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: clymene-agent
    spec:
      containers:
        - name: clymene-agent
          image: bourbonkk/clymene-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 15691
            - containerPort: 15692
          args:
            - --config.file=/etc/clymene/clymene.yml
            - --prometheus.remote.url=http://prometheus.monitors.svc.cluster.local:9090/api/v1/write
            - --log-level=info
          env:
            - name: TS_STORAGE_TYPE
              value: kafka
          volumeMounts:
            - mountPath: /etc/clymene/
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: clymene-agent-config
      securityContext:
        runAsUser: 1000

```

And the error is 

`Error: unknown flag: --prometheus.remote.url`

Is there something wrong with my yaml file? or did I miss something? 

If you have time please let me know : )
